development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: busation@gmail.com
  :password: lkys_123
  :enable_starttls_auto: true
production:
  :address: localhost
  :port: 25
  :domain: my.aksts.ru
  :authentication: plain
  :user_name: info@aksts.ru
  :password: 12345678m
  :enable_starttls_auto: true