development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: busation@gmail.com
  :password: lkys_123
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: busation@gmail.com
  :password: lkys_123
  :enable_starttls_auto: true